### PR TITLE
Use Github Actions to build and deploy the website

### PR DESCRIPTION
**Pull request by leouieda**
Replaces TravisCI and doctr. It's a lot simpler to set up and actually
runs faster (though that's not a big issue here).

### CODE REVIEW

**Comment by leouieda** [comment]
I was experimenting with Github Actions a bit and decided to try this as a test. It worked perfectly for my own website so porting it here as well. Setup was actually pretty straight forward. I had to setup deploy keys since we need to push to a different repository but the instructions here were easy to follow: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key

This might work for the project docs as well with some modification since we need to maintain the older versions of the docs in the gh-pages branch.

**Comment by seisman** [comment]
I also find github actions easier to use and understand. 

Recently, @weiji14 and I also migrated most of the CI jobs of the PyGMT project from Azure Pipelines to GitHub Actions.

**Comment by weiji14** [comment]
Yeah, there was a lot of work doing the CI migration (especially with the cache!) but I think it's worth it, I much prefer viewing the logs on Github than Azure Pipelines (though technically they're both Azure according to [this](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#cloud-hosts-for-github-hosted-runners)).

**Comment by leouieda** [comment]
I saw that (going through my notifications is was what made me look into this actually). Thanks for doing all of that! I’m going to experiment on a test project with the docs and PyPI deployments.

**Pull request merged**
