### PR TITLE
Update website for 6.1.1 release

### PR DESCRIPTION
**Pull request by PaulWessel**
Also update some older news items.

### CODE REVIEW

**Review by seisman — COMMENTED** [review]
Need to update the documentation page. It still says 6.1.0
image

**Comment by PaulWessel** [comment]
Yep.  Should it just say 6.1.1 instead, since the docs are the same, no?

**Review by seisman — APPROVED** [review]

**Comment by PaulWessel** [comment]
Odd space in the workshops index file.  Should that .. raw:: html be moved up?

**Comment by seisman** [comment]
> Odd space in the workshops index file. Should that .. raw:: html be moved up?

Yes

**Pull request merged**
