### PR TITLE
WIP: Add a raw changelog for 6.1 to website

### PR DESCRIPTION
**Pull request by PaulWessel**
This new file Release_6.1.html shows a raw list of changes in 6.1.  We can either keep it this way or add formatting.  In either case, need @seisman help to hook it into a news item for the release of 6.1.  So this is a WIP PR for now. I scraped the git history @seisman sent me to extract this list.  Both he and @joa-quim should examine this list and look for missed items.  Since file was > 10000 lines it is possible I clipped something.  I am not listing any of the bug-fixes, just features and modules.  There are many other things that could deserve a mention (CMake build improvements, for one), CI improvements, API additions, but most of those are not of interest to most.  Please add what you think should be added, and revise any entry that you feel is unclear.

### CODE REVIEW

**Comment by seisman** [comment]
Are you going to list the changes in the GMT main site instead of the gmt documentation site?

**Comment by PaulWessel** [comment]
Hm what do you thing? Shall we have a shorter more general statement for the website without listing things and then have something like what I write as a rst file for the documentation page?

**Comment by seisman** [comment]
> Shall we have a shorter more general statement for the website without listing things and then have something like what I write as a rst file for the documentation page?

Yes, that's what I expect.

This is how PyGMT does. Here is a release announcement for [PyGMT v0.1.1](https://forum.generic-mapping-tools.org/t/pygmt-v0-1-1-released/483). It only lists the most important changes and then links to the [full change history](https://www.pygmt.org/v0.1.1/changes.html).

**Comment by PaulWessel** [comment]
OK, I am re-discovering the changes.rst file in our docs, so I will place the detailed stuff there.  I guess when ready we compose a release message for the forum and add a news link to it on the main site?

**Comment by seisman** [comment]
> I guess when ready we compose a release message for the forum and add a news link to it on the main site?

I think so. Users who subscribe to the Announcement channel can at least get a notification.

**Comment by seisman** [comment]
Like this one https://forum.generic-mapping-tools.org/t/gmt-6-0-0-is-released/35.

**Pull request closed without merging**
