### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by Esteban82**
I add Paul's award of the AGU 2022. Please check the english.

### CODE REVIEW

**Review by maxrjones — COMMENTED** [review]
The news/index.rst page hosts older news items. It would be better to add this to the news section of the homepage (https://github.com/GenericMappingTools/website/blob/Add_AGU2022_Award/index.rst#news) and move one or more older items to this section.

**Comment by seisman** [comment]
Ping @Esteban82

**Comment by seisman** [comment]
> The news/index.rst page hosts older news items. It would be better to add this to the news section of the homepage ([`Add_AGU2022_Award`/index.rst#news](https://github.com/GenericMappingTools/website/blob/Add_AGU2022_Award/index.rst?rgh-link-date=2022-09-16T15%3A54%3A41Z#news)) and move one or more older items to this section.

@Esteban82 As mentioned by @maxrjones, need to update the root [index.rst](https://github.com/GenericMappingTools/website/blob/master/index.rst) file instead.

**Comment by Esteban82** [comment]
Sorry, I merge it automatically. I will try to do it ASAP.

**Pull request merged**
