### PR TITLE
Add a video of Paul's 20 years of GMT talk

### PR DESCRIPTION
**Pull request by leouieda**
Embed the video in the About page and also link to the original.

### CODE REVIEW

**Comment by leouieda** [comment]
@PaulWessel want to add some more context for this video or is that enough?

**Comment by leouieda** [comment]
Where?

**Comment by PaulWessel** [comment]
In the sentence "However, GMT 5 is generall backwards compatible with GMT 4 syntax"

**Comment by leouieda** [comment]
The y is there. That's not affected by this PR. I think it's just Github truncating at x characters.

**Comment by PaulWessel** [comment]
OK, WILL APPROVE.

**Comment by PaulWessel** [comment]
Sorry about caps.

**Pull request merged**
