### PR TITLE
Update index.rst to announce release of PyGMT 0.3.0

### PR DESCRIPTION
**Pull request by michaelgrund**

### CODE REVIEW

**Comment by seisman** [comment]
Looks good!

**Comment by joa-quim** [comment]
Shouldn't we only have a link to the latest rleased version? Imagine that I would add the 26 (soon 27) versions of GMT.jl?

**Comment by seisman** [comment]
> Shouldn't we only have a link to the latest rleased version? Imagine that I would add the 26 (soon 27) versions of GMT.jl?

Yes, I agree. @michaelgrund  Are you willing to help delete the entries for old PyGMT versions?

**Comment by michaelgrund** [comment]
> 
> 
> > Shouldn't we only have a link to the latest rleased version? Imagine that I would add the 26 (soon 27) versions of GMT.jl?
> 
> Yes, I agree. @michaelgrund Are you willing to help delete the entries for old PyGMT versions?

Also agree, I opened a PR (#96) and removed the entries for versions 0.1.0 and 0.2.0.

**Pull request merged**
